version: "3.5"
services:
  100-web-backend:
    build:
      context: ./web/100-signedsealed/src/backend
    environment:
      - LOG_JSON=true
      - LOG_LEVEL=trace
      - DB_PATH=signedsealed.db
      - FLAG=BSidesPDX{5f0505ea-72d1-40c4-8451-d4a3e19e7491}
    ports:
      - 48323:8080
  100-web-frontend:
    build:
      context: ./web/100-signedsealed/src/frontend
      args:
        API_URL: http://localhost:48323 # should point to the external address of the backend
    ports:
      - 48324:8080
    depends_on:
      - 100-web-backend
  200-web-minio:
    build:
      context: ./web/200-yourstruly/src/minio
    network_mode: host # host networking so presigned URLs work
    environment:
      - MINIO_ACCESS_KEY=IL0B9GDKIR7XCKYZWNS6
      - MINIO_SECRET_KEY=IxhrKLZVZ17P2uR0xDvs1kxxuJ7zCKLYkeilXFpi
  200-web-store:
    build:
      context: ./web/200-yourstruly/src/store
    network_mode: host # only so 200-web-backend can access it in host mode :/
  200-web-backend:
    build:
      context: ./web/200-yourstruly/src/backend
    network_mode: host # host networking so we can access minio at the same address as the host for presigned URLs to work
    environment:
      - CHARACTER_SERVICE_URL=http://localhost:8080
      - MINIO_ENDPOINT=localhost:9000 # public address of minio
      - MINIO_ACCESS_KEY_ID=IL0B9GDKIR7XCKYZWNS6
      - MINIO_SECRET_ACCESS_KEY=IxhrKLZVZ17P2uR0xDvs1kxxuJ7zCKLYkeilXFpi
    depends_on:
      - 200-web-store
      - 200-web-minio
  300-web-mongodb:
    image: mongo
  300-web-vulnerable-backend:
    build:
      context: ./web/300-helljs/src/vulnerable-backend
    environment:
      - JWT_SECRET=6330a524-2c2a-43e9-b240-651dc6d2d19c # must be the same as secure-backend!!!
      - MONGODB_URL=mongodb://300-web-mongodb:27017
      - MONGODB_DB_NAME=helljs
      - PORT=8080
    ports:
      - 27331:8080
    depends_on:
      - 300-web-mongodb
  300-web-secure-backend:
    build:
      context: ./web/300-helljs/src/secure-backend
    environment:
      - JWT_SECRET=6330a524-2c2a-43e9-b240-651dc6d2d19c # must be the same as vulnerable-backend!!!
      - PORT=8080
    ports:
      - 27332:8080
  300-web-frontend:
    build:
      context: ./web/300-helljs/src/frontend
      args:
        VULNERABLE_API_URL: http://localhost:27331 # should point to the external address of the vulnerable backend
        SECURE_API_URL: http://localhost:27332 # should point to the external address of the secure backend
    ports:
      - 27330:8080
    depends_on:
      - 300-web-secure-backend
      - 300-web-vulnerable-backend
