apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web100-frontend
spec:
  replicas: 1
  template:
    metadata:
      name: web100-frontend
      labels:
        app: web100-frontend
    spec:
      containers:
        - name: web100-frontend
          image: phx.ocir.io/oke/bsidespdx2019/web100_frontend:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
          - containerPort: 8080
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ocirsecret
