apiVersion: apps/v1
kind: Deployment
metadata:
  name: web200-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web200-store
  template:
    metadata:
      name: web200-store
      labels:
        app: web200-store
    spec:
      containers:
        - name: web200-store
          image: phx.ocir.io/oke/bsidespdx2019/web200_store:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
          - containerPort: 8080
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ocirsecret
