apiVersion: v1
kind: Service
metadata:
  name: web200-minio
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web200objectstorage.bsidespdxctf.party
spec:
  ports:
   - port: 9000
     targetPort: 9000
  selector:
    app: web200-minio
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web200-minio
spec:
  podSelector:
    matchLabels:
      app: web200-minio
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 9000
    from: []
