apiVersion: apps/v1
kind: Deployment
metadata:
  name: web300-vulnerable-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web300-vulnerable-backend
  template:
    metadata:
      name: web300-vulnerable-backend
      labels:
        app: web300-vulnerable-backend
    spec:
      containers:
        - name: web300-vulnerable-backend
          image: phx.ocir.io/oke/bsidespdx2019/web300_vulnerable_backend:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
          - containerPort: 8080
          env:
          - name: JWT_SECRET
            value: "6330a524-2c2a-43e9-b240-651dc6d2d19c"
          - name: MONGODB_URL
            value: "mongodb://mongo.bsidespdxctf:27017"
          - name: MONGODB_DB_NAME
            value: "helljs"
          - name: PORT
            value: "8080"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ocirsecret
