apiVersion: v1
kind: Service
metadata:
  name: web300-frontend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web300.bsidespdxctf.party
spec:
  ports:
   - port: 27330
     targetPort: 8080
  selector:
    app: web300-frontend
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web300-frontend
spec:
  podSelector:
    matchLabels:
      app: web300-frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8080
    from: []
