apiVersion: v1
kind: Service
metadata:
  name: web300-vulnerable-backend
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web300backend-a.bsidespdxctf.party
spec:
  ports:
   - port: 27331
     targetPort: 8080
  selector:
    app: web300-vulnerable-backend
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: web300-vulnerable-backend
spec:
  podSelector:
    matchLabels:
      app: web300-vulnerable-backend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8080
    from: []
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 169.254.169.254/32
          - 10.96.0.1/32
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    - port: 27017
      protocol: TCP
