apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pwn100
spec:
  replicas: 1
  template:
    metadata:
      name: pwn100
      labels:
        app: pwn100
    spec:
      containers:
        - name: pwn100
          image: phx.ocir.io/oke/bsidespdx2019/pwn100:latest
          imagePullPolicy: Always
          securityContext:
            privileged: false
          ports:
          - containerPort: 1337
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ocirsecret
